name: PHP tests

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy .env file
        run: cp .env.example .env

      - name: Configure Composer cache
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-suggest --no-progress --prefer-dist

      - name: Generate application key
        run: php artisan key:generate

      - name: Configure NPM cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install NPM dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Compile NPM dependencies
        run: npm run prod

      - name: Run PHPUnit tests
        run: php vendor/bin/phpunit

      - name: Upload logs
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Logs
          path: ./storage/logs
